### ISSUE TITLE
IE 11 ignoring cache headers on schema API endpoint

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-mfa#393]
IE 11 caches the schema API response that provides the MFA app all of its context on available methods, registered methods, whether the process can be skipped and even the CSRF token to use. This causes issues when state changes happen, such as:

- MFA becomes mandatory (the Skip button still appears)
- An MFA method is added / removed / enabled on the site
- The user logs in repeatedly (the CSRF token gets stale, breaking the auth flow)

I believe this can be resolved by adding `Pragma: no-cache`, as other recommended anti-caching headers are already present, and no other browser seems to exhibit this behaviour.

**Comment by robbieaverill** [comment]
One day people will stop using Internet Explorer and the world will be a better place.

**Comment by emteknetnz** [comment]
Potentially fixed in https://github.com/silverstripe/silverstripe-mfa/pull/417

**Comment by Cheddam** [comment]
Regression testing against MFA 4.2.1 has revealed that #417 does not fix this issue for IE 11. `HTTPCacheControlMiddleware` does not make use of `Pragma: no-cache`.

Worth noting that #417 only disabled caching for authentication endpoints, missing registration endpoints and the main `schema` endpoint.

**Comment by emteknetnz** [comment]
It shouldn't matter about the lack of `Pragma: no-cache`?  That's a very old header which, according to [Microsoft docs](https://docs.microsoft.com/en-US/troubleshoot/browsers/how-to-prevent-caching#the-pragma-no-cache-header), is for use with HTTP 1.0, as opposed to HTTP 1.1 which supports the `Cache-control` header

To confirm, are you able to try adding in the Pramga: no-cache in HTTPCacheControlMiddleware on your setup to see if it fixes things for IE11?

**Comment by Cheddam** [comment]
Yeah, my bad - I was conflating one issue with another. The actual problem is the latter one - two of the API endpoints (schema and registration) are still missing the cache disabling logic. IE 11 does _not_ cache the authentication endpoint, which has had the fix applied.

I've raised #422 to address this.

**Comment by emteknetnz** [comment]
Linked PR has been merged and released as 4.2.2.
